# Generated by Django 2.1.5 on 2019-01-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=70)),
                ('esal', models.IntegerField()),
                ('erole', models.CharField(max_length=25)),
            ],
        ),
    ]
