# Generated by Django 2.1.7 on 2019-03-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190322_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='publications',
        ),
        migrations.AddField(
            model_name='link',
            name='article',
            field=models.ManyToManyField(to='testapp.Article'),
        ),
        migrations.AddField(
            model_name='link',
            name='publication',
            field=models.ManyToManyField(to='testapp.Publication'),
        ),
    ]
