# Generated by Django 2.1.7 on 2019-03-22 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20190322_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='article',
        ),
        migrations.AddField(
            model_name='link',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.Article'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='link',
            name='publication',
        ),
        migrations.AddField(
            model_name='link',
            name='publication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.Publication'),
            preserve_default=False,
        ),
    ]
