# Generated by Django 2.1.7 on 2019-03-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate',
            name='service',
            field=models.CharField(default='labour', max_length=40),
            preserve_default=False,
        ),
    ]
