# Generated by Django 2.1.7 on 2019-03-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190321_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_creation',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
