# Generated by Django 2.1.7 on 2019-03-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_individual_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='img',
            field=models.ImageField(null=True, upload_to='templates/testapp'),
        ),
    ]
