# Generated by Django 2.1.7 on 2019-03-31 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_auto_20190329_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_contrib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('budget', models.IntegerField()),
                ('event_id', models.ForeignKey(on_delete='CASCADE', to='accounts.event_creation')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='individual',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
